package pu.imdb.dal;

import pu.imdb.util.StringHelper;

public class JavaClassPath
{

public static void main( String [] args )
{
	StringHelper.printClassPath();
	@SuppressWarnings( "unused" )
	int pipo = 0;

}

/**
/home/purbanus/.m2/repository/antlr/antlr/2.7.7/antlr-2.7.7.jar
/home/purbanus/.m2/repository/ch/qos/logback/logback-classic/1.2.11/logback-classic-1.2.11.jar
/home/purbanus/.m2/repository/ch/qos/logback/logback-core/1.2.11/logback-core-1.2.11.jar
/home/purbanus/.m2/repository/com/fasterxml/classmate/1.5.1/classmate-1.5.1.jar
/home/purbanus/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.13.4/jackson-annotations-2.13.4.jar
/home/purbanus/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.13.4/jackson-core-2.13.4.jar
/home/purbanus/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.13.4.2/jackson-databind-2.13.4.2.jar
/home/purbanus/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.13.4/jackson-datatype-jdk8-2.13.4.jar
/home/purbanus/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.13.4/jackson-datatype-jsr310-2.13.4.jar
/home/purbanus/.m2/repository/com/fasterxml/jackson/module/jackson-module-parameter-names/2.13.4/jackson-module-parameter-names-2.13.4.jar
/home/purbanus/.m2/repository/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar
/home/purbanus/.m2/repository/com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3.jar
/home/purbanus/.m2/repository/com/google/guava/guava/25.0-jre/guava-25.0-jre.jar
/home/purbanus/.m2/repository/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar
/home/purbanus/.m2/repository/com/h2database/h2/1.4.200/h2-1.4.200.jar
/home/purbanus/.m2/repository/com/jayway/jsonpath/json-path/2.6.0/json-path-2.6.0.jar
/home/purbanus/.m2/repository/com/shapesecurity/salvation2/3.0.0/salvation2-3.0.0.jar
/home/purbanus/.m2/repository/com/squareup/okhttp3/okhttp/3.14.9/okhttp-3.14.9.jar
/home/purbanus/.m2/repository/com/squareup/okio/okio/1.14.0/okio-1.14.0.jar
/home/purbanus/.m2/repository/com/sun/activation/jakarta.activation/1.2.2/jakarta.activation-1.2.2.jar
/home/purbanus/.m2/repository/com/sun/istack/istack-commons-runtime/3.0.12/istack-commons-runtime-3.0.12.jar
/home/purbanus/.m2/repository/com/sun/mail/jakarta.mail/1.6.7/jakarta.mail-1.6.7.jar
/home/purbanus/.m2/repository/com/vaadin/external/google/android-json/0.0.20131108.vaadin1/android-json-0.0.20131108.vaadin1.jar
/home/purbanus/.m2/repository/com/zaxxer/HikariCP/4.0.3/HikariCP-4.0.3.jar
/home/purbanus/.m2/repository/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
/home/purbanus/.m2/repository/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
/home/purbanus/.m2/repository/commons-net/commons-net/3.8.0/commons-net-3.8.0.jar
/home/purbanus/.m2/repository/io/micrometer/micrometer-core/1.8.12/micrometer-core-1.8.12.jar
/home/purbanus/.m2/repository/jakarta/activation/jakarta.activation-api/1.2.2/jakarta.activation-api-1.2.2.jar
/home/purbanus/.m2/repository/jakarta/annotation/jakarta.annotation-api/1.3.5/jakarta.annotation-api-1.3.5.jar
/home/purbanus/.m2/repository/jakarta/persistence/jakarta.persistence-api/2.2.3/jakarta.persistence-api-2.2.3.jar
/home/purbanus/.m2/repository/jakarta/transaction/jakarta.transaction-api/1.3.3/jakarta.transaction-api-1.3.3.jar
/home/purbanus/.m2/repository/jakarta/validation/jakarta.validation-api/2.0.2/jakarta.validation-api-2.0.2.jar
/home/purbanus/.m2/repository/jakarta/xml/bind/jakarta.xml.bind-api/2.3.3/jakarta.xml.bind-api-2.3.3.jar
/home/purbanus/.m2/repository/net/bytebuddy/byte-buddy-agent/1.11.22/byte-buddy-agent-1.11.22.jar
/home/purbanus/.m2/repository/net/bytebuddy/byte-buddy/1.11.22/byte-buddy-1.11.22.jar
/home/purbanus/.m2/repository/net/minidev/accessors-smart/2.4.8/accessors-smart-2.4.8.jar
/home/purbanus/.m2/repository/net/minidev/json-smart/2.4.8/json-smart-2.4.8.jar
/home/purbanus/.m2/repository/net/sourceforge/htmlunit/htmlunit-core-js/2.54.0/htmlunit-core-js-2.54.0.jar
/home/purbanus/.m2/repository/net/sourceforge/htmlunit/htmlunit-cssparser/1.10.0/htmlunit-cssparser-1.10.0.jar
/home/purbanus/.m2/repository/net/sourceforge/htmlunit/htmlunit/2.54.0/htmlunit-2.54.0.jar
/home/purbanus/.m2/repository/net/sourceforge/htmlunit/neko-htmlunit/2.54.0/neko-htmlunit-2.54.0.jar
/home/purbanus/.m2/repository/no/api/freemarker/freemarker-java8/2.0.0/freemarker-java8-2.0.0.jar
/home/purbanus/.m2/repository/org/apache/commons/commons-collections4/4.4/commons-collections4-4.4.jar
/home/purbanus/.m2/repository/org/apache/commons/commons-exec/1.3/commons-exec-1.3.jar
/home/purbanus/.m2/repository/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
/home/purbanus/.m2/repository/org/apache/commons/commons-text/1.9/commons-text-1.9.jar
/home/purbanus/.m2/repository/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
/home/purbanus/.m2/repository/org/apache/httpcomponents/httpcore/4.4.15/httpcore-4.4.15.jar
/home/purbanus/.m2/repository/org/apache/httpcomponents/httpmime/4.5.13/httpmime-4.5.13.jar
/home/purbanus/.m2/repository/org/apache/logging/log4j/log4j-api/2.17.2/log4j-api-2.17.2.jar
/home/purbanus/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.17.2/log4j-to-slf4j-2.17.2.jar
/home/purbanus/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/9.0.69/tomcat-embed-core-9.0.69.jar
/home/purbanus/.m2/repository/org/apache/tomcat/embed/tomcat-embed-el/9.0.69/tomcat-embed-el-9.0.69.jar
/home/purbanus/.m2/repository/org/apache/tomcat/embed/tomcat-embed-websocket/9.0.69/tomcat-embed-websocket-9.0.69.jar
/home/purbanus/.m2/repository/org/apiguardian/apiguardian-api/1.1.2/apiguardian-api-1.1.2.jar
/home/purbanus/.m2/repository/org/aspectj/aspectjweaver/1.9.7/aspectjweaver-1.9.7.jar
/home/purbanus/.m2/repository/org/assertj/assertj-core/3.21.0/assertj-core-3.21.0.jar
/home/purbanus/.m2/repository/org/brotli/dec/0.1.2/dec-0.1.2.jar
/home/purbanus/.m2/repository/org/checkerframework/checker-compat-qual/2.0.0/checker-compat-qual-2.0.0.jar
/home/purbanus/.m2/repository/org/checkerframework/checker-qual/3.5.0/checker-qual-3.5.0.jar
/home/purbanus/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.jar
/home/purbanus/.m2/repository/org/eclipse/jetty/jetty-client/9.4.49.v20220914/jetty-client-9.4.49.v20220914.jar
/home/purbanus/.m2/repository/org/eclipse/jetty/jetty-http/9.4.49.v20220914/jetty-http-9.4.49.v20220914.jar
/home/purbanus/.m2/repository/org/eclipse/jetty/jetty-io/9.4.49.v20220914/jetty-io-9.4.49.v20220914.jar
/home/purbanus/.m2/repository/org/eclipse/jetty/jetty-util/9.4.49.v20220914/jetty-util-9.4.49.v20220914.jar
/home/purbanus/.m2/repository/org/eclipse/jetty/websocket/websocket-api/9.4.49.v20220914/websocket-api-9.4.49.v20220914.jar
/home/purbanus/.m2/repository/org/eclipse/jetty/websocket/websocket-client/9.4.49.v20220914/websocket-client-9.4.49.v20220914.jar
/home/purbanus/.m2/repository/org/eclipse/jetty/websocket/websocket-common/9.4.49.v20220914/websocket-common-9.4.49.v20220914.jar
/home/purbanus/.m2/repository/org/freemarker/freemarker/2.3.31/freemarker-2.3.31.jar
/home/purbanus/.m2/repository/org/glassfish/jaxb/jaxb-runtime/2.3.7/jaxb-runtime-2.3.7.jar
/home/purbanus/.m2/repository/org/glassfish/jaxb/txw2/2.3.7/txw2-2.3.7.jar
/home/purbanus/.m2/repository/org/hamcrest/hamcrest/2.2/hamcrest-2.2.jar
/home/purbanus/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.12/HdrHistogram-2.1.12.jar
/home/purbanus/.m2/repository/org/hibernate/common/hibernate-commons-annotations/5.1.2.Final/hibernate-commons-annotations-5.1.2.Final.jar
/home/purbanus/.m2/repository/org/hibernate/hibernate-core/5.6.14.Final/hibernate-core-5.6.14.Final.jar
/home/purbanus/.m2/repository/org/hibernate/validator/hibernate-validator/6.2.5.Final/hibernate-validator-6.2.5.Final.jar
/home/purbanus/.m2/repository/org/jboss/jandex/2.4.2.Final/jandex-2.4.2.Final.jar
/home/purbanus/.m2/repository/org/jboss/logging/jboss-logging/3.4.3.Final/jboss-logging-3.4.3.Final.jar
/home/purbanus/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.8.2/junit-jupiter-api-5.8.2.jar
/home/purbanus/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.8.2/junit-jupiter-engine-5.8.2.jar
/home/purbanus/.m2/repository/org/junit/jupiter/junit-jupiter-params/5.8.2/junit-jupiter-params-5.8.2.jar
/home/purbanus/.m2/repository/org/junit/jupiter/junit-jupiter/5.8.2/junit-jupiter-5.8.2.jar
/home/purbanus/.m2/repository/org/junit/platform/junit-platform-commons/1.8.2/junit-platform-commons-1.8.2.jar
/home/purbanus/.m2/repository/org/junit/platform/junit-platform-engine/1.8.2/junit-platform-engine-1.8.2.jar
/home/purbanus/.m2/repository/org/latencyutils/LatencyUtils/2.0.3/LatencyUtils-2.0.3.jar
/home/purbanus/.m2/repository/org/mockito/mockito-core/4.0.0/mockito-core-4.0.0.jar
/home/purbanus/.m2/repository/org/mockito/mockito-junit-jupiter/4.0.0/mockito-junit-jupiter-4.0.0.jar
/home/purbanus/.m2/repository/org/objenesis/objenesis/3.2/objenesis-3.2.jar
/home/purbanus/.m2/repository/org/opentest4j/opentest4j/1.2.0/opentest4j-1.2.0.jar
/home/purbanus/.m2/repository/org/ow2/asm/asm/9.1/asm-9.1.jar
/home/purbanus/.m2/repository/org/postgresql/postgresql/42.3.8/postgresql-42.3.8.jar
/home/purbanus/.m2/repository/org/projectlombok/lombok/1.18.24/lombok-1.18.24.jar
/home/purbanus/.m2/repository/org/seleniumhq/selenium/htmlunit-driver/2.54.0/htmlunit-driver-2.54.0.jar
/home/purbanus/.m2/repository/org/seleniumhq/selenium/selenium-api/3.141.59/selenium-api-3.141.59.jar
/home/purbanus/.m2/repository/org/seleniumhq/selenium/selenium-chrome-driver/3.141.59/selenium-chrome-driver-3.141.59.jar
/home/purbanus/.m2/repository/org/seleniumhq/selenium/selenium-edge-driver/3.141.59/selenium-edge-driver-3.141.59.jar
/home/purbanus/.m2/repository/org/seleniumhq/selenium/selenium-firefox-driver/3.141.59/selenium-firefox-driver-3.141.59.jar
/home/purbanus/.m2/repository/org/seleniumhq/selenium/selenium-ie-driver/3.141.59/selenium-ie-driver-3.141.59.jar
/home/purbanus/.m2/repository/org/seleniumhq/selenium/selenium-java/3.141.59/selenium-java-3.141.59.jar
/home/purbanus/.m2/repository/org/seleniumhq/selenium/selenium-opera-driver/3.141.59/selenium-opera-driver-3.141.59.jar
/home/purbanus/.m2/repository/org/seleniumhq/selenium/selenium-remote-driver/3.141.59/selenium-remote-driver-3.141.59.jar
/home/purbanus/.m2/repository/org/seleniumhq/selenium/selenium-safari-driver/3.141.59/selenium-safari-driver-3.141.59.jar
/home/purbanus/.m2/repository/org/seleniumhq/selenium/selenium-support/3.141.59/selenium-support-3.141.59.jar
/home/purbanus/.m2/repository/org/skyscreamer/jsonassert/1.5.1/jsonassert-1.5.1.jar
/home/purbanus/.m2/repository/org/slf4j/jul-to-slf4j/1.7.36/jul-to-slf4j-1.7.36.jar
/home/purbanus/.m2/repository/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.jar
/home/purbanus/.m2/repository/org/springframework/boot/spring-boot-actuator-autoconfigure/2.6.14/spring-boot-actuator-autoconfigure-2.6.14.jar
/home/purbanus/.m2/repository/org/springframework/boot/spring-boot-actuator/2.6.14/spring-boot-actuator-2.6.14.jar
/home/purbanus/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.6.14/spring-boot-autoconfigure-2.6.14.jar
/home/purbanus/.m2/repository/org/springframework/boot/spring-boot-configuration-processor/2.6.14/spring-boot-configuration-processor-2.6.14.jar
/home/purbanus/.m2/repository/org/springframework/boot/spring-boot-devtools/2.6.14/spring-boot-devtools-2.6.14.jar
/home/purbanus/.m2/repository/org/springframework/boot/spring-boot-starter-actuator/2.6.14/spring-boot-starter-actuator-2.6.14.jar
/home/purbanus/.m2/repository/org/springframework/boot/spring-boot-starter-aop/2.6.14/spring-boot-starter-aop-2.6.14.jar
/home/purbanus/.m2/repository/org/springframework/boot/spring-boot-starter-data-jdbc/2.6.14/spring-boot-starter-data-jdbc-2.6.14.jar
/home/purbanus/.m2/repository/org/springframework/boot/spring-boot-starter-data-jpa/2.6.14/spring-boot-starter-data-jpa-2.6.14.jar
/home/purbanus/.m2/repository/org/springframework/boot/spring-boot-starter-freemarker/2.6.14/spring-boot-starter-freemarker-2.6.14.jar
/home/purbanus/.m2/repository/org/springframework/boot/spring-boot-starter-jdbc/2.6.14/spring-boot-starter-jdbc-2.6.14.jar
/home/purbanus/.m2/repository/org/springframework/boot/spring-boot-starter-json/2.6.14/spring-boot-starter-json-2.6.14.jar
/home/purbanus/.m2/repository/org/springframework/boot/spring-boot-starter-logging/2.6.14/spring-boot-starter-logging-2.6.14.jar
/home/purbanus/.m2/repository/org/springframework/boot/spring-boot-starter-mail/2.6.14/spring-boot-starter-mail-2.6.14.jar
/home/purbanus/.m2/repository/org/springframework/boot/spring-boot-starter-test/2.6.14/spring-boot-starter-test-2.6.14.jar
/home/purbanus/.m2/repository/org/springframework/boot/spring-boot-starter-tomcat/2.6.14/spring-boot-starter-tomcat-2.6.14.jar
/home/purbanus/.m2/repository/org/springframework/boot/spring-boot-starter-validation/2.6.14/spring-boot-starter-validation-2.6.14.jar
/home/purbanus/.m2/repository/org/springframework/boot/spring-boot-starter-web/2.6.14/spring-boot-starter-web-2.6.14.jar
/home/purbanus/.m2/repository/org/springframework/boot/spring-boot-starter/2.6.14/spring-boot-starter-2.6.14.jar
/home/purbanus/.m2/repository/org/springframework/boot/spring-boot-test-autoconfigure/2.6.14/spring-boot-test-autoconfigure-2.6.14.jar
/home/purbanus/.m2/repository/org/springframework/boot/spring-boot-test/2.6.14/spring-boot-test-2.6.14.jar
/home/purbanus/.m2/repository/org/springframework/boot/spring-boot/2.6.14/spring-boot-2.6.14.jar
/home/purbanus/.m2/repository/org/springframework/data/spring-data-commons/2.6.10/spring-data-commons-2.6.10.jar
/home/purbanus/.m2/repository/org/springframework/data/spring-data-jdbc/2.3.10/spring-data-jdbc-2.3.10.jar
/home/purbanus/.m2/repository/org/springframework/data/spring-data-jpa/2.6.10/spring-data-jpa-2.6.10.jar
/home/purbanus/.m2/repository/org/springframework/data/spring-data-relational/2.3.10/spring-data-relational-2.3.10.jar
/home/purbanus/.m2/repository/org/springframework/spring-aop/5.3.24/spring-aop-5.3.24.jar
/home/purbanus/.m2/repository/org/springframework/spring-aspects/5.3.24/spring-aspects-5.3.24.jar
/home/purbanus/.m2/repository/org/springframework/spring-beans/5.3.24/spring-beans-5.3.24.jar
/home/purbanus/.m2/repository/org/springframework/spring-context-support/5.3.24/spring-context-support-5.3.24.jar
/home/purbanus/.m2/repository/org/springframework/spring-context/5.3.24/spring-context-5.3.24.jar
/home/purbanus/.m2/repository/org/springframework/spring-core/5.3.24/spring-core-5.3.24.jar
/home/purbanus/.m2/repository/org/springframework/spring-expression/5.3.24/spring-expression-5.3.24.jar
/home/purbanus/.m2/repository/org/springframework/spring-jcl/5.3.24/spring-jcl-5.3.24.jar
/home/purbanus/.m2/repository/org/springframework/spring-jdbc/5.3.24/spring-jdbc-5.3.24.jar
/home/purbanus/.m2/repository/org/springframework/spring-orm/5.3.24/spring-orm-5.3.24.jar
/home/purbanus/.m2/repository/org/springframework/spring-test/5.3.24/spring-test-5.3.24.jar
/home/purbanus/.m2/repository/org/springframework/spring-tx/5.3.24/spring-tx-5.3.24.jar
/home/purbanus/.m2/repository/org/springframework/spring-web/5.3.24/spring-web-5.3.24.jar
/home/purbanus/.m2/repository/org/springframework/spring-webmvc/5.3.24/spring-webmvc-5.3.24.jar
/home/purbanus/.m2/repository/org/xmlunit/xmlunit-core/2.8.4/xmlunit-core-2.8.4.jar
/home/purbanus/.m2/repository/org/yaml/snakeyaml/1.29/snakeyaml-1.29.jar
/home/purbanus/.m2/repository/xalan/serializer/2.7.2/serializer-2.7.2.jar
/home/purbanus/.m2/repository/xalan/xalan/2.7.2/xalan-2.7.2.jar
/home/purbanus/.m2/repository/xerces/xercesImpl/2.12.0/xercesImpl-2.12.0.jar
/home/purbanus/.m2/repository/xml-apis/xml-apis/1.4.01/xml-apis-1.4.01.jar
/home/purbanus/prog/eclipse/sts-4.18.0.RELEASE/plugins/org.hamcrest.core_1.3.0.v20180420-1519.jar
/home/purbanus/prog/eclipse/sts-4.18.0.RELEASE/plugins/org.junit_4.13.2.v20211018-1956.jar
/home/purbanus/projecten/git/pu.imdb/pu.imdb/target/classes
/home/purbanus/projecten/git/pu.imdb/pu.imdb/target/test-classes
/home/purbanus/projecten/workspaces/sts4.12.1/alg.lib/lib/iris-standaard/jt400-8.6.jar
/home/purbanus/projecten/workspaces/sts4.12.1/base.java/bin
/home/purbanus/projecten/workspaces/sts4.12.1/base.java/bintest
/home/purbanus/projecten/workspaces/sts4.12.1/base.java/lib/bundles/log4j-1.2.17.jar
/home/purbanus/projecten/workspaces/sts4.12.1/base.java/lib/bundles/sshj-0.9.0.jar
/home/purbanus/projecten/workspaces/sts4.12.1/base.java/lib/jars/commons-httpclient-3.1.jar
/home/purbanus/projecten/workspaces/sts4.12.1/base.java/lib/jars/easymock-3.4.jar
/home/purbanus/projecten/workspaces/sts4.12.1/base.java/lib/jars/glassfish-corba-omgapi-4.2.1.jar
/home/purbanus/projecten/workspaces/sts4.12.1/base.java/lib/jars/hibernate-core-4.3.6.Final.jar
/home/purbanus/projecten/workspaces/sts4.12.1/base.java/lib/jars/hsqldb-2.3.3.jar
/home/purbanus/projecten/workspaces/sts4.12.1/base.java/lib/jars/jcl-over-slf4j-1.7.21.jar
/home/purbanus/projecten/workspaces/sts4.12.1/base.java/lib/jars/jdom2-2.0.6.jar
/home/purbanus/projecten/workspaces/sts4.12.1/base.java/lib/jars/mybatis-3.3.0.jar
/home/purbanus/projecten/workspaces/sts4.12.1/base.java/lib/jars/mybatis-generator-core-1.3.2.jar
/home/purbanus/projecten/workspaces/sts4.12.1/base.java/lib/jars/mybatis-spring-1.2.3.jar
/home/purbanus/projecten/workspaces/sts4.12.1/base.java/lib/jars/slf4j-api-1.7.21.jar
/home/purbanus/projecten/workspaces/sts4.12.1/base.java/lib/jars/slf4j-log4j12-1.7.21.jar
/home/purbanus/projecten/workspaces/sts4.12.1/base.java/lib/jars/spring-aop-5.3.24.jar
/home/purbanus/projecten/workspaces/sts4.12.1/base.java/lib/jars/spring-beans-5.3.24.jar
/home/purbanus/projecten/workspaces/sts4.12.1/base.java/lib/jars/spring-context-5.3.24.jar
/home/purbanus/projecten/workspaces/sts4.12.1/base.java/lib/jars/spring-context-support-5.3.24.jar
/home/purbanus/projecten/workspaces/sts4.12.1/base.java/lib/jars/spring-core-5.3.24.jar
/home/purbanus/projecten/workspaces/sts4.12.1/base.java/lib/jars/spring-expression-5.3.24.jar
/home/purbanus/projecten/workspaces/sts4.12.1/base.java/lib/jars/spring-jdbc-5.3.24.jar
/home/purbanus/projecten/workspaces/sts4.12.1/base.java/lib/jars/spring-test-5.3.24.jar
/home/purbanus/projecten/workspaces/sts4.12.1/base.java/lib/jars/spring-tx-5.3.24.jar
/home/purbanus/projecten/workspaces/sts4.12.1/base.java/lib/jars/spring-ws-core-2.2.0.RELEASE.jar
/home/purbanus/projecten/workspaces/sts4.12.1/base.java/lib/jars/velocity-1.7.jar
/home/purbanus/projecten/workspaces/sts4.12.1/base.java/lib/jars/velocity-tools-2.0.jar
/opt/tomcat9/lib/annotations-api.jar
/opt/tomcat9/lib/catalina-ant.jar
/opt/tomcat9/lib/catalina-ha.jar
/opt/tomcat9/lib/catalina-ssi.jar
/opt/tomcat9/lib/catalina-storeconfig.jar
/opt/tomcat9/lib/catalina-tribes.jar
/opt/tomcat9/lib/catalina.jar
/opt/tomcat9/lib/ecj-4.20.jar
/opt/tomcat9/lib/el-api.jar
/opt/tomcat9/lib/jasper-el.jar
/opt/tomcat9/lib/jasper.jar
/opt/tomcat9/lib/jaspic-api.jar
/opt/tomcat9/lib/jsp-api.jar
/opt/tomcat9/lib/servlet-api.jar
/opt/tomcat9/lib/tomcat-api.jar
/opt/tomcat9/lib/tomcat-coyote.jar
/opt/tomcat9/lib/tomcat-dbcp.jar
/opt/tomcat9/lib/tomcat-i18n-cs.jar
/opt/tomcat9/lib/tomcat-i18n-de.jar
/opt/tomcat9/lib/tomcat-i18n-es.jar
/opt/tomcat9/lib/tomcat-i18n-fr.jar
/opt/tomcat9/lib/tomcat-i18n-ja.jar
/opt/tomcat9/lib/tomcat-i18n-ko.jar
/opt/tomcat9/lib/tomcat-i18n-pt-BR.jar
/opt/tomcat9/lib/tomcat-i18n-ru.jar
/opt/tomcat9/lib/tomcat-i18n-zh-CN.jar
/opt/tomcat9/lib/tomcat-jdbc.jar
/opt/tomcat9/lib/tomcat-jni.jar
/opt/tomcat9/lib/tomcat-util-scan.jar
/opt/tomcat9/lib/tomcat-util.jar
/opt/tomcat9/lib/tomcat-websocket.jar
/opt/tomcat9/lib/websocket-api.jar

 */
}
